### ISSUE TITLE
Tz-Nummer 

### ISSUE THREAD

**Issue by deingithub** [derf/Travel-Status-DE-DBWagenreihung#1]
Moin,
danke für das echt schnelle Update der Library auf die neue Wagenreihungs-API! Eine Sache ist mir beim Upgrade auf die neue Version aufgefallen:
https://github.com/derf/Travel-Status-DE-DBWagenreihung/blob/6f47465a52e056f9fe6d1290828fd449b6aaa808/lib/Travel/Status/DE/DBWagenreihung/Group.pm#L83-L90
Die Triebzugnummer (also zb "ICE1101") wird in der API-Response von bahn.de nicht unter `group.transport.name`, sondern direkt in `group.name` ausgegeben. Die von DBWagenreihung ausgegebene Tz-Nummer ist also immer undef. Vgl. dieselbe Stelle in der travelynx-Umsetzung, wo es funktioniert:
https://github.com/derf/travelynx/blob/78d4494364a577ac2c17ffef36a8020b66d76654/lib/Travelynx.pm#L1297-L1305

**Comment by derf** [comment]
Hoppla. Danke für den Hinweis, Bugfix-Release folgt zeitnah :)
